"""empty message

Revision ID: 05d99e0d0f61
Revises: 45857bb30159
Create Date: 2017-12-30 15:16:17.293880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d99e0d0f61'
down_revision = '45857bb30159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('fname', sa.String(length=256), nullable=False),
    sa.Column('lname', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('events_db', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events_db', 'user_db', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events_db', type_='foreignkey')
    op.drop_column('events_db', 'created_by')
    op.drop_table('user_db')
    # ### end Alembic commands ###
