"""empty message

Revision ID: 19efde2f48ba
Revises: 3c9cac49bcf9
Create Date: 2018-01-15 20:04:52.800708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19efde2f48ba'
down_revision = '3c9cac49bcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_db', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_db', 'category')
    # ### end Alembic commands ###
