"""empty message

Revision ID: 3c9cac49bcf9
Revises: 05d99e0d0f61
Create Date: 2018-01-13 13:59:23.079804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9cac49bcf9'
down_revision = '05d99e0d0f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvps',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_db.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_db.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvps')
    # ### end Alembic commands ###
