"""empty message

Revision ID: 45857bb30159
Revises: 
Create Date: 2017-12-29 22:45:37.100412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45857bb30159'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_db')
    # ### end Alembic commands ###
