"""empty message

Revision ID: 493467d07285
Revises: 19efde2f48ba
Create Date: 2018-01-15 23:00:01.184795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493467d07285'
down_revision = '19efde2f48ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
